### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mfaheemakhtar** [motdotla/dotenv-expand#25]
The link "test/.env" is broken on npm.

**Comment by ericrallen** [comment]
@mfaheemakhtar Sorry for the delay, could you be more specific? I'd be happy to take a look if you can explain the expected behavior and the actual behavior you are seeing.

Thanks!

**Comment by mfaheemakhtar** [comment]
@ericrallen,

Go to https://www.npmjs.com/package/dotenv-expand and scroll down. The last sentence, "See test/.env for examples of variable expansion in your .env file." has a link, which is broken.

**Comment by ericrallen** [comment]
@mfaheemakhtar Thanks for the explanation. It looks like that link is using a relative URL that works in the GitHub rendered `README.md` found at https://github.com/motdotla/dotenv-expand/, but when it's rendered on npm that relative URL doesn't work.

We should update it to point to `https://github.com/motdotla/dotenv-expand/blob/master/test/.env` so that the link works in both contexts.

**Comment by mfaheemakhtar** [comment]
@ericrallen , yes this is exactly the issue.
